# Generated by Django 4.1.4 on 2024-05-10 08:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('StudentDean', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='placement',
            name='Stud_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.user'),
        ),
        migrations.AddField(
            model_name='dorm',
            name='Block',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='StudentDean.block'),
        ),
        migrations.AddField(
            model_name='block',
            name='Block_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.blocktype'),
        ),
        migrations.AddField(
            model_name='announcementstatus',
            name='announcement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='StudentDean.announcement'),
        ),
        migrations.AddField(
            model_name='announcementstatus',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
