# Generated by Django 5.1.3 on 2024-12-01 10:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StudentDean', '0003_attendancemachine'),
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendancemachine',
            name='ip',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='attendancemachine',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='attendancemachine',
            name='port',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='attendancemachine',
            name='status',
            field=models.CharField(choices=[('Connected', 'Connected'), ('Not-Connected', 'Not-Connected')], default='Not-Connected', max_length=255),
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateTimeField()),
                ('attendance_machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='StudentDean.attendancemachine')),
                ('block_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='StudentDean.block')),
                ('student_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.user')),
            ],
        ),
    ]
