# Generated by Django 5.1.3 on 2024-12-01 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StudentDean', '0004_alter_attendancemachine_ip_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendancemachine',
            name='port',
            field=models.IntegerField(default=4370),
        ),
    ]
