# Generated by Django 4.1.4 on 2024-05-10 08:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('StudentDean', '0001_initial'),
        ('Proctor', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='reportproblem',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='properties',
            name='block',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='StudentDean.block'),
        ),
        migrations.AddField(
            model_name='properties',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='StudentDean.dorm'),
        ),
        migrations.AddField(
            model_name='material',
            name='proctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proctor', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='material',
            name='property',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='property', to='Proctor.properties'),
        ),
        migrations.AddField(
            model_name='material',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='exit_permission_requst',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sender1', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='exit_permission',
            name='proctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proctor1', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='exit_permission',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student1', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='borrow_request',
            name='property',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='property1', to='Proctor.properties'),
        ),
        migrations.AddField(
            model_name='borrow_request',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sender', to=settings.AUTH_USER_MODEL),
        ),
    ]
